# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'EIIM S4 Unit (225be0b6-6988-4b65-8268-8fec4d0ff5f2)'
    subscriptionId: '225be0b6-6988-4b65-8268-8fec4d0ff5f2'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Test_POC'
    location: 'Brazil US'
    templateLocation: 'URL of the file'
    csmFile: 'https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json'
    csmParametersFile: 'https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json'
    #overrideParameters: '-dailyreports_name ''$(IACWeb)'' -dailyreportsapi_name ''$(IACAPI)'''
    deploymentMode: 'Incremental'
    deploymentName: 'AzureLogicAPPD1'
    deploymentOutputs: 'AzureLogicAPPD1'