# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'EIIM S4 Unit(225be0b6-6988-4b65-8268-8fec4d0ff5f2)'
    subscriptionId: '225be0b6-6988-4b65-8268-8fec4d0ff5f2'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Test_POC'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/deepikathuyamani/AzureLogicAppsD.git'
    overrideParameters: '-projectName Test Project 1'
    deploymentMode: 'Incremental'