# Starter pipeline
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'EIIM S4 Unit (225be0b6-6988-4b65-8268-8fec4d0ff5f2)'
    subscriptionId: '225be0b6-6988-4b65-8268-8fec4d0ff5f2'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Reference_POCs_RG'
    location: 'East US'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'
    deploymentName: 'Initial HTTP Service Deployment'
    deploymentOutputs: 'SO'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
